services:
  junoscommander:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: junoscommander
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_MODE=development
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=junoscommander
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_SSL_MODE=disable
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - DEV_AUTH_BYPASS=true
      - TEST_USERNAME=brandon.seaver
      - TEST_PASSWORD=test123
    networks:
      - junoscommander-net
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  openldap:
    image: osixia/openldap:1.5.0
    container_name: junoscommander-ldap
    environment:
      LDAP_ORGANISATION: "Example Corp"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN: "dc=example,dc=com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_TLS: "false"
    ports:
      - "389:389"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    networks:
      - junoscommander-net
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: junoscommander-ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    depends_on:
      - openldap
    networks:
      - junoscommander-net
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: junoscommander-db
    environment:
      POSTGRES_DB: junoscommander
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - junoscommander-net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: junoscommander-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - junoscommander-net
    restart: unless-stopped

networks:
  junoscommander-net:
    driver: bridge

volumes:
  ldap-data:
  ldap-config:
  postgres-data:
  redis-data: